unit Test.PCharVal;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.PCharVal;

type
  // Test methods for class TTestSettingParamGetter

  TestTTestSettingParamGetter = class(TTestCase)
  strict private
    FPCharString: PChar;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetValuesFromForm;
  end;

implementation

procedure TestTTestSettingParamGetter.SetUp;
begin
  FPCharString := PChar('');
end;

procedure TestTTestSettingParamGetter.TearDown;
begin
end;

procedure TestTTestSettingParamGetter.TestGetValuesFromForm;
begin
  CheckEquals(PCharToInt(PChar(String('0')), 1), 0);
  CheckEquals(PCharToInt(PChar(String('100')), 3), 100);
  CheckEquals(PCharToInt(PChar(String('2147483647')), 10), 2147483647);
  CheckEquals(PCharToInt(PChar(String('-2147483648')), 11), -2147483648);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTTestSettingParamGetter.Suite);
end.

